#!/bin/bash

export CIRCLE_SHA1=CHANGEME
export CIRCLE_TOKEN=CHANGEME
export GITHUB_TOKEN=CHANGEME
export CIRCLE_BUILD_NUM=CHANGEME
export CIRCLE_PROJECT_USERNAME=CHANGEME
export CIRCLE_PROJECT_REPONAME=CHANGEME
